### ISSUE TITLE
逻辑有冗余

### ISSUE THREAD

**Issue by shuhuaxie** [GuJin/Crash#1]
感谢博主的分享帮我解决了问题,我本地调试发现
`mDefaultUncaughtExceptionHandler.uncaughtException(thread, ex);`
这段代码没有也是可以正常使用的,因为bugly会调用自己设置的Handler

**Comment by GuJin** [comment]
您的 bugly 和 自己的 UncaughtExceptionHandler 的初始化顺序是怎样的呢？

**Comment by shuhuaxie** [comment]
跟博主的顺序一样. 先自定义UncaughtExceptionHandler,后使用bugly 初始化.
 catchUncaughtException();
CrashReport.initCrashReport(getApplicationContext(), "****", false);
不过也没啥影响,不然就这样吧Q.Q
